[package]
name    = "syft_python"
version = "0.1.0"
authors = ["Ben Szymkow <simcof@gmail.com>", "Madhava Jay <me@madhavajay.com>"]
edition = "2018"

[lib]
name       = "syft"
crate-type = ["cdylib"]

[dependencies]
syft  = { version = "^0", path = "../../syft" }
pyo3  = { version = "0.13.2", features = ["extension-module"] }
tokio = { version = "1.6.0", features = ["full"] }
prost = "0.7.0"
