name: Core

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build Rust Core
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - name: Install protoc
        run: |
          PROTOC_VERSION=3.12.3
          curl -LO "https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-linux-x86_64.zip"
          unzip -d "${GITHUB_WORKSPACE}" "protoc-${PROTOC_VERSION}-linux-x86_64.zip" bin/protoc
          chmod +x "${GITHUB_WORKSPACE}/bin/protoc"
          ${GITHUB_WORKSPACE}/bin/protoc --version
          export PATH=${GITHUB_WORKSPACE}/bin/:$PATH
          which protoc
          echo "::set-env name=PATH::$PATH"
      - name: Build
        working-directory: ./syft
        run: |
          which protoc
          cargo build --verbose
      - name: Run tests
        working-directory: ./syft
        run: cargo test --verbose
